### PR TITLE
[feature] add unit display

### PR DESCRIPTION
**Pull request by shaolin405mi16**
Hi again, this is my third (and the last so far) pull request.

Sometimes you may want to display a unit (℃, cm, kg, mmHg, etc.) next to number picker(s).
This patch adds an option `unit` (which defaults to empty string).
I hope you feel it nifty.

My only concern is, since the modal picker uses an ionic grid system to display number pickers (and minus sign, decimal point), I'm afraid this trivial change (to the html files) will break bilateral symmetry on the picker dialog.

Let me know what you think.

### CODE REVIEW

**Comment by mdridley** [comment]
I like it. I was doing the label in the output on my form, but I can see the benefit of having it there. To keep the balance, look at how I did the negative portion and adjust the cols to equal back out. Should work then for most people's needs. Also can you make sure to add the new parameter to the ReadMe?

**Comment by shaolin405mi16** [comment]
Unlike the negative portion, this unit portion may not always be the same width. When I adjust the whole area to keep the balance when using "mmHg", it will not look good when the unit is "m" ... this is why I didn't apply "col-??" class to this unit label.

**Comment by shaolin405mi16** [comment]
Also, will add the new parameter to the ReadMe for sure (sorry for that)

**Comment by mdridley** [comment]
Hmmm, was thinking if you account for the col, if it has the space either way, the col width would be preserved, so like Col-10 will always be 10% spacing. It is late and been a long week, so I might be wrong. I can try it out tomorrow with a fresh head. Thank you!

**Pull request merged**
